cloud:
  aws:
    credentials:
      access-key: AKIA43CGW6CNL5YKY2AI
      secret-key: 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
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: hireashelf.com



spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080